# Generated by Django 6.0 on 2025-12-27 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productinquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinquiry',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='productinquiry',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('quoted', 'Quoted'), ('follow_up', 'Follow Up'), ('converted', 'Converted'), ('closed', 'Closed')], default='new', max_length=20),
        ),
    ]
