# Generated by Django 6.0 on 2025-12-27 05:25

import apps.master.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productinquiry_priority_productinquiry_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=apps.master.models.upload_with_uuid),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.ImageField(upload_to=apps.master.models.upload_with_uuid),
        ),
    ]
