# Generated by Django 6.0 on 2025-12-27 05:25

import apps.master.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_teammember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default=datetime.datetime(2025, 12, 27, 5, 25, 17, 206952, tzinfo=datetime.timezone.utc), upload_to=apps.master.models.upload_with_uuid),
            preserve_default=False,
        ),
    ]
